# Generated by Django 3.1.6 on 2021-02-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_requested_password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
